@startuml day
[*] --> 朝

state 朝{
    起床 --> 洗顔
    洗顔 --> 着替え
    着替え --> 登校準備
    登校準備 --> 朝食
    朝食 --> 登校
            state 登校{
                外に出る --> 金沢駅 : 徒歩か自転車
                金沢駅 --> 電車 : 7:40発七尾行
                電車 --> 津幡駅 : 8:55頃到着
                津幡駅 --> 学校 : 8:20頃到着
            }
    登校 --> 学校到着
    学校到着 --> 朝の暇つぶし

}


@enduml day